[features]
seeds = false
[programs.devnet]
tipsea_solana = "4fAkJwnBu84Ey1ikVrpJTSvFxZyahCoBuMdcHn4TMGad"
[registry]
url = "https://anchor.projectserum.com"
[provider]
cluster = "devnet"
wallet = "/Volumes/SecureKey/Files/tipsea_prog.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
