[features]
seeds = false
[programs.devnet]
tipsea_solana = "4HMaj1cDxfbunTUW7Nrz7j1nKQRKqGoUt8r7pFQsAJd5"
[registry]
url = "https://anchor.projectserum.com"
[provider]
cluster = "devnet"
wallet = "/Users/gabrielunruh/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
