[features]
seeds = false
[programs.devnet]
tipsea_solana = "61V6pS8v5ZY19tUrtMZAwUHuEJidx4aTViGXJ9pNsJXv"
[registry]
url = "https://anchor.projectserum.com"
[provider]
cluster = "devnet"
wallet = "/Users/gabrielunruh/.config/solana/tipsea_prog.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
