[features]
seeds = false
[programs.devnet]
tipsea_solana = "9gxkAobRDsTv3E5T8nteySZhYr4j87hC8K7b2ZiyqP5m"
[registry]
url = "https://anchor.projectserum.com"
[provider]
cluster = "devnet"
wallet = "/Users/gabrielunruh/.config/solana/tipsea_prog.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
